---
title: "Lasso: Hitters"
author: "Max Glonek"
date: "Trimester `r if(as.integer(format(Sys.time(),'%m'))<5){1}else if(as.integer(format(Sys.time(),'%m'))<9){2}else{3}`, `r format(Sys.time(),'%Y')`"
output: 
  html_document:
    theme: default
    number_sections: yes
    df_print: paged
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  fig.width = 6,
  fig.asp = 0.618,
  out.width = "70%",
  fig.align = "center",
  root.dir = '../'
)
pacman::p_load(tidyverse, tidymodels, vip, ggridges, viridis, magrittr, ISLR, janitor)
theme_set(theme_bw())
```

# Get the Data

```{r}
data("Hitters", package = "ISLR")
hitters <- as_tibble(Hitters)
hitters
```

# Cleaning

## Clean Variable Names

```{r}
hitters %<>% janitor::clean_names()
hitters
```

## Remove NA Values

```{r}
hitters %<>% drop_na()
hitters
```

## Create Train and Test Splits

```{r}
hitters_split <- initial_split(hitters, strata = salary)
hitters_train <- training(hitters_split)
hitters_test <- testing(hitters_split)
```

#Workflow

## Recipe

```{r}
hitters_recipe <- recipe(salary ~ ., data = hitters) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_dummy(all_nominal_predictors())
hitters_recipe %>% prep() %>% bake(new_data = NULL)
hitters_recipe %>% prep() %>% bake(new_data = NULL) %>% pull(salary)
```

## Model

```{r}
hitters_model <- linear_reg(mixture = 1, penalty = tune()) %>%
  set_engine("glmnet") %>%
  set_mode("regression")
hitters_model
```

## Workflow

```{r}
hitters_wf <- workflow() %>%
  add_model(hitters_model) %>%
  add_recipe(hitters_recipe)
hitters_wf
```

# Tuning

## Penalty Grid

```{r}
#hitters_grid <- grid_regular(penalty(), levels = 50)
hitters_grid <- tibble(penalty = seq(.5,50,.5))
hitters_grid
```

## Cross Validation Folds

```{r}
set.seed(2022)
hitters_cv <- vfold_cv(hitters_train, strata = salary)
hitters_cv
```

## Tune Model (Penalty Term)

```{r}
doParallel::registerDoParallel()
hitters_tune <- tune_grid(object = hitters_wf,
                          resamples = hitters_cv,
                          grid = hitters_grid)
hitters_tune %>% collect_metrics()
```

# Decide on a Model

```{r}
p <- hitters_tune %>%
  collect_metrics() %>%
  filter(.metric == "rmse") %>%
  ggplot(aes(penalty, mean)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean - std_err, ymax = mean + std_err))
p
```

```{r}
plotly::ggplotly(p)
```

```{r}
show_best(hitters_tune, metric = "rmse", n = 10)
(M1 <- select_best(hitters_tune, metric = "rmse"))
M2 <- select_by_one_std_err(hitters_tune, metric = "rmse", penalty)
select_by_pct_loss(hitters_tune, metric = "rmse", penalty, limit = 5)
```

# Finalise the Model

```{r}
hitters_final_model <- hitters_wf %>% finalize_workflow(M1)
hitters_final_model
```

# Variable Importance

```{r}
hitters_final_model %>%
  fit(hitters_train) %>%
  extract_fit_parsnip() %>%
  vip()
```

# Evaluate Model Performance Using Testing Data

```{r}
hitters_final_model %>% last_fit(hitters_split) %>% collect_metrics()
```

```{r}
hitters_test %>%
  add_column(hitters_final_model %>%
               fit(data = hitters_train) %>%
               predict(new_data = hitters_test)) %>%
  rmse(salary, .pred)
```