---
title: |
    | STATS 7022 - Data Science
    | Seminar 4: Plots
author: "Max Glonek"
institute: "School of Computer and Mathematical Sciences, University of Adelaide"
date: "Trimester `r if(as.integer(format(Sys.time(),'%m'))<5){1}else if(as.integer(format(Sys.time(),'%m'))<9){2}else{3}`, `r format(Sys.time(),'%Y')`"
output:
  pdf_document: default
  beamer_presentation:
    includes:
      in_header: header.tex
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  warning = FALSE, 
  message = FALSE, 
  fig.width = 6, 
  fig.asp = 0.618, 
  out.width = "100%",
  fig.align = "center", 
  root.dir = '../'
)
```

## Set-Up

```{r}
pacman::p_load(tidyverse, plotly, patchwork)
```

## Plotly

```{r, eval = FALSE}
p <- mpg %>% 
  ggplot(aes(
    displ, cty, 
    col = drv, 
    text = glue::glue("Model: {model}"))) + 
  geom_point()
ggplotly(p)
```

## Maths in Plots
\small
```{r, eval = FALSE}
mpg %>% 
  ggplot(aes(displ, cty)) + 
  geom_point() + 
  labs(
    x = expression(mu[1] + rho^2),
    y = expression(pi), 
    title = expression(
      paste("Plot with ", alpha, " and ", beta)
    )
  ) + 
  annotate("text", 
           x = 4, y = 30, 
           label = expression(
             Y[i] == beta[0] + beta[1] * x[i] + epsilon[i]
             ), 
           size = 5)
```

## Maths in Plots

```{r, echo = FALSE}
mpg %>% 
  ggplot(aes(displ, cty)) + 
  geom_point() + 
  labs(
    x = expression(mu[1] + rho^2),
    y = expression(pi), 
    title = expression(
      paste("Plot with ", alpha, " and ", beta)
    )
  ) + 
  annotate("text", 
           x = 4, y = 30, 
           label = expression(
             Y[i] == beta[0] + beta[1] * x[i] + epsilon[i]
             ), 
           size = 5)
```

## Patchwork

```{r}
p1 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + 
  geom_boxplot(aes(gear, disp, group = gear))
p3 <- ggplot(mtcars) + 
  geom_bar(aes(carb))
```

## Patchwork: Side-by-Side

```{r}
p1 | p2
```

## Patchwork: Layers

```{r}
(p1 | p2) / p3
```


## Task: Plotly (Code)

```{r, eval = FALSE, echo = TRUE}
data("txhousing", package = "ggplot2")
library(scales)
p <- ggplot(txhousing, aes(date, median)) + 
  geom_line(aes(
    group = city, 
    text = paste("City:", city, "| Median:",median)
  ))
ggplotly(p, tooltip = c("text")) %>% 
  style(hoverlabel = list(bgcolor = "white"))
```

## Task: Expression
\small
```{r}
df <- tibble(
  x = rnorm(1000, mean = 5, sd = 2)
)
```

```{r, echo = TRUE}
m <- round(mean(df$x), 2)
sd <- round(var(df$x), 2)
df %>% 
  ggplot(aes(x)) + 
  geom_histogram(col = "black", fill = "orange") + 
  ggtitle(
    bquote(
      paste(bar(x)," = ", .(m), " | ", s^2, " = ", .(sd))
    )
  ) + 
  annotate(
    "text", x = 9, y = 75, 
    label = expression(Y %~% N(mu, sigma^2)), 
    size = 5
  )
```

## Task: Patchwork

```{r, echo = TRUE}
(p1 | p2) / p3 + 
  plot_annotation(
    title = 'Plots from mtcars',
    subtitle = '
    Plot A - scatterplot; 
    Plot B - side-by-side boxplot; 
    Plot C - barchart',
caption = 'Disclaimer: None of these plots are insightful', 
tag_levels = "A"
  )
```

## Resources

- https://www.benjaminackerman.com/blog/2019-03-formatting-math-symbols-and-expressions-in-ggplot-labels/
- https://github.com/ropensci/plotly
- https://patchwork.data-imaginist.com/