---
title: "Cross Validation: Titanic"
author: "Max Glonek"
date: "Trimester `r if(as.integer(format(Sys.time(),'%m'))<5){1}else if(as.integer(format(Sys.time(),'%m'))<9){2}else{3}`, `r format(Sys.time(),'%Y')`"
output:
  html_document:
    number_sections: yes
    df_print: paged
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  fig.width = 6, 
  fig.asp = 0.618, 
  out.width = "70%",
  fig.align = "center", 
  root.dir = '../'
)
pacman::p_load(tidyverse, tidymodels, titanic, janitor, paletteer)
theme_set(theme_bw())
```

# Load data

```{r}
data("titanic_train", package = "titanic")
titanic <- as_tibble(titanic_train)
titanic
```

# Clean names

```{r}
titanic <- titanic %>% clean_names()
titanic
```

# Convert survived to factor

```{r}
titanic <- titanic %>% 
  mutate_all(factor)
titanic
```

# Split into training and test

```{r}
titanic_split <- initial_split(titanic, strata = survived)
titanic_train <- training(titanic_split)
titanic_test <- testing(titanic_split)
```

```{r}
titanic_train
```
```{r}
titanic_test
```


# Get CV of training

```{r}
titanic_cv <- vfold_cv(titanic_train, v = 5, strata = survived)
titanic_cv
```


# Set up workflow

## Recipe

```{r}
titanic_recipe <- 
  recipe(survived ~ sex + pclass, data = titanic_train) %>% 
  step_dummy(all_predictors()) %>% 
  step_interact(terms = ~starts_with("sex"):starts_with("pclass"))
```

```{r}
titanic_recipe %>% prep() %>% juice()
```

## Model

```{r}
titanic_model <- logistic_reg() %>% set_engine("glm")
```

```{r}
titanic_wf <- workflow() %>% 
  add_recipe(titanic_recipe) %>% 
  add_model(titanic_model)
titanic_wf
```

```{r}
titanic_fit <- fit(titanic_wf, titanic_train)
titanic_fit %>% tidy()
```

# Fit CV

```{r}
titanic_fits <- fit_resamples(
  titanic_wf, 
  resamples = titanic_cv, 
  control = control_resamples(save_pred = TRUE)
)
titanic_fits
```


# Get metrics

```{r}
titanic_fits %>% collect_metrics()
```
# ROC curves

```{r}
CV_ROC <- 
  titanic_fits %>% 
  collect_predictions() %>% 
  group_by(id) %>% 
  roc_curve(truth = survived, .pred_1, event_level = "second")
CV_ROC %>% autoplot()
```


# Compare to test

```{r}
titanic_test %>% 
  add_column(
    predict(titanic_fit, new_data = titanic_test, type = "prob")
  ) %>% 
  roc_auc(truth = survived, .pred_1, event_level = "second")
```

```{r}
test_ROC <- titanic_test %>% 
  add_column(
    predict(titanic_fit, new_data = titanic_test, type = "prob")
  ) %>% 
  roc_curve(truth = survived, .pred_1, event_level = "second") %>% 
  add_column(id = "test")
bind_rows(CV_ROC, test_ROC) %>% 
  ggplot(aes(1 - specificity, sensitivity, col = id)) + geom_path() + 
  scale_color_brewer(palette = "Set2")
```

