---
title: "Decision Tree: Titanic"
author: "Max Glonek"
date: "Trimester `r if(as.integer(format(Sys.time(),'%m'))<5){1}else if(as.integer(format(Sys.time(),'%m'))<9){2}else{3}`, `r format(Sys.time(),'%Y')`"
output: 
  html_document:
    theme: default
    number_sections: yes
    df_print: paged
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
 echo = TRUE, 
 fig.width = 6, 
 fig.asp = 0.618, 
 out.width = "70%",
 fig.align = "center", 
  root.dir = '../'
)
```

# Libs

```{r}
pacman::p_load(tidyverse, tidymodels, janitor, visNetwork)
```

# Load data

```{r}
data("titanic_train", package = "titanic")
titanic <- as_tibble(titanic_train)
titanic
```

# Clean names

```{r}
titanic <- titanic %>% clean_names()
titanic
```

# Convert survived, pclass to factor

```{r}
titanic <- titanic %>% 
  mutate_at(vars(survived, pclass, sex), factor)
titanic
```

# Select survived, pclass, age, sib_sp, parch

```{r}
titanic <- titanic %>% select(survived, pclass, sex, age, sib_sp, parch)
titanic
```

# Set recipe

```{r}
titanc_recipe <- recipe(survived ~ ., data = titanic)
```

# Set model

```{r}
titanic_model <- decision_tree(mode = "classification") %>% 
  set_engine("rpart")
```

# Set workflow

```{r}
titanic_wf <- workflow() %>% 
  add_recipe(titanc_recipe) %>% 
  add_model(titanic_model)
```

# Fit model

```{r}
titanic_fit <- titanic_wf %>% fit(titanic) %>% pull_workflow_fit()
titanic_fit
```

```{r}
plot(titanic_fit$fit)
text(titanic_fit$fit)
```

```{r}
visTree(titanic_fit$fit)
```

# Predict

```{r}
jono <- tibble(
  pclass = "3", 
  sex = "male", 
  age = 51, 
  sib_sp = 1, 
  parch = 0
)
predict(titanic_fit, new_data = jono)
predict(titanic_fit, new_data = jono, type = "prob")
```